% export_pulse_table.m
meta = struct( ...
    'geom',   struct('sb',sb,'sp',sp,'L1',L1,'L2',L2), ...
    'volume', struct('xr',xr,'yr',yr,'zr',zr,'nx',nx,'ny',ny,'nz',nz), ...
    'cal',    struct('k_us',k_us,'pw_home',pw_home,'sgn',sgn, ...
                     'pw_min',pw_min,'pw_max',pw_max), ...
    'built',  datetime('now'));

T = array2table(pulse_table, 'VariableNames', ...
    {'idx','x','y','z','th1','th2','th3','pw1','pw2','pw3','valid'});

save('pulse_table.mat','T','meta');
writetable(T,'pulse_table.csv');